"""Update DailyReport, new value actual_balance

Revision ID: 0b10d9d09979
Revises: 465ce0f364a1
Create Date: 2021-09-27 21:49:12.605795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b10d9d09979'
down_revision = '465ce0f364a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_report', sa.Column('actual_balance', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('daily_report', 'actual_balance')
    # ### end Alembic commands ###
