"""Cascade delete from storage and shop

Revision ID: 0cac8f6e5886
Revises: e966337348a4
Create Date: 2022-01-03 16:19:31.028635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cac8f6e5886'
down_revision = 'e966337348a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_by_weight_amount'), 'by_weight', ['amount'], unique=False)
    op.create_index(op.f('ix_by_weight_money'), 'by_weight', ['money'], unique=False)
    op.create_index(op.f('ix_by_weight_product_name'), 'by_weight', ['product_name'], unique=False)
    op.create_index(op.f('ix_collection_fund_money'), 'collection_fund', ['money'], unique=False)
    op.create_index(op.f('ix_deposit_fund_money'), 'deposit_fund', ['money'], unique=False)
    op.create_index(op.f('ix_expense_is_global'), 'expense', ['is_global'], unique=False)
    op.create_index(op.f('ix_expense_money'), 'expense', ['money'], unique=False)
    op.create_index(op.f('ix_supply_amount'), 'supply', ['amount'], unique=False)
    op.create_index(op.f('ix_supply_money'), 'supply', ['money'], unique=False)
    op.create_index(op.f('ix_supply_product_name'), 'supply', ['product_name'], unique=False)
    op.create_index(op.f('ix_transfer_product_amount'), 'transfer_product', ['amount'], unique=False)
    op.create_index(op.f('ix_transfer_product_product_name'), 'transfer_product', ['product_name'], unique=False)
    op.create_index(op.f('ix_write_off_amount'), 'write_off', ['amount'], unique=False)
    op.create_index(op.f('ix_write_off_product_name'), 'write_off', ['product_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_write_off_product_name'), table_name='write_off')
    op.drop_index(op.f('ix_write_off_amount'), table_name='write_off')
    op.drop_index(op.f('ix_transfer_product_product_name'), table_name='transfer_product')
    op.drop_index(op.f('ix_transfer_product_amount'), table_name='transfer_product')
    op.drop_index(op.f('ix_supply_product_name'), table_name='supply')
    op.drop_index(op.f('ix_supply_money'), table_name='supply')
    op.drop_index(op.f('ix_supply_amount'), table_name='supply')
    op.drop_index(op.f('ix_expense_money'), table_name='expense')
    op.drop_index(op.f('ix_expense_is_global'), table_name='expense')
    op.drop_index(op.f('ix_deposit_fund_money'), table_name='deposit_fund')
    op.drop_index(op.f('ix_collection_fund_money'), table_name='collection_fund')
    op.drop_index(op.f('ix_by_weight_product_name'), table_name='by_weight')
    op.drop_index(op.f('ix_by_weight_money'), table_name='by_weight')
    op.drop_index(op.f('ix_by_weight_amount'), table_name='by_weight')
    # ### end Alembic commands ###
