"""fix role

Revision ID: 0d4603bb79a0
Revises: f7ab36da14e8
Create Date: 2021-09-13 22:09:26.580325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d4603bb79a0'
down_revision = 'f7ab36da14e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('barista_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['barista_id'], ['barista.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], )
    )
    op.drop_table('permissions')
    op.drop_table('roles_users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles_users',
    sa.Column('barista_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['barista_id'], ['barista.id'], name='roles_users_barista_id_fkey'),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], name='roles_users_role_id_fkey')
    )
    op.create_table('permissions',
    sa.Column('barista_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['barista_id'], ['barista.id'], name='permissions_barista_id_fkey'),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], name='permissions_role_id_fkey')
    )
    op.drop_table('roles')
    # ### end Alembic commands ###
