"""Initial migration.

Revision ID: 41a02719dde8
Revises: 
Create Date: 2021-08-14 12:57:21.678403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41a02719dde8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('barista',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('phone_number', sa.String(length=120), nullable=True),
    sa.Column('salary_rate', sa.Integer(), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_index(op.f('ix_barista_name'), 'barista', ['name'], unique=True)
    op.create_table('coffee_shop',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('place_name', sa.String(length=64), nullable=True),
    sa.Column('address', sa.String(length=120), nullable=True),
    sa.Column('cash', sa.Integer(), nullable=True),
    sa.Column('cashless', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coffee_shop_address'), 'coffee_shop', ['address'], unique=True)
    op.create_index(op.f('ix_coffee_shop_place_name'), 'coffee_shop', ['place_name'], unique=True)
    op.create_table('expense',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('type_cost', sa.String(length=64), nullable=True),
    sa.Column('money', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expense_category'), 'expense', ['category'], unique=True)
    op.create_index(op.f('ix_expense_timestamp'), 'expense', ['timestamp'], unique=False)
    op.create_index(op.f('ix_expense_type_cost'), 'expense', ['type_cost'], unique=True)
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('coffee_shop_equipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coffee_machine', sa.String(length=64), nullable=True),
    sa.Column('grinder_1', sa.String(length=64), nullable=True),
    sa.Column('grinder_2', sa.String(length=64), nullable=True),
    sa.Column('coffee_shop_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['coffee_shop_id'], ['coffee_shop.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coffee_shop_equipment_coffee_machine'), 'coffee_shop_equipment', ['coffee_machine'], unique=True)
    op.create_index(op.f('ix_coffee_shop_equipment_grinder_1'), 'coffee_shop_equipment', ['grinder_1'], unique=True)
    op.create_index(op.f('ix_coffee_shop_equipment_grinder_2'), 'coffee_shop_equipment', ['grinder_2'], unique=True)
    op.create_table('daily_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coffee_shop_id', sa.Integer(), nullable=True),
    sa.Column('barista_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('cashbox', sa.Integer(), nullable=True),
    sa.Column('cash_balance', sa.Integer(), nullable=True),
    sa.Column('cashless', sa.Integer(), nullable=True),
    sa.Column('remainder_of_day', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['barista_id'], ['barista.id'], ),
    sa.ForeignKeyConstraint(['coffee_shop_id'], ['coffee_shop.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_report_timestamp'), 'daily_report', ['timestamp'], unique=False)
    op.create_table('roles_users',
    sa.Column('barista_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['barista_id'], ['barista.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], )
    )
    op.create_table('warehouse',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coffee_arabika', sa.Integer(), nullable=True),
    sa.Column('coffee_blend', sa.Integer(), nullable=True),
    sa.Column('milk', sa.Integer(), nullable=True),
    sa.Column('panini', sa.Integer(), nullable=True),
    sa.Column('hot_dogs', sa.Integer(), nullable=True),
    sa.Column('coffee_shop_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['coffee_shop_id'], ['coffee_shop.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('expenses',
    sa.Column('expense_id', sa.Integer(), nullable=False),
    sa.Column('daily_report_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['daily_report_id'], ['daily_report.id'], ),
    sa.ForeignKeyConstraint(['expense_id'], ['expense.id'], ),
    sa.PrimaryKeyConstraint('expense_id', 'daily_report_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('expenses')
    op.drop_table('warehouse')
    op.drop_table('roles_users')
    op.drop_index(op.f('ix_daily_report_timestamp'), table_name='daily_report')
    op.drop_table('daily_report')
    op.drop_index(op.f('ix_coffee_shop_equipment_grinder_2'), table_name='coffee_shop_equipment')
    op.drop_index(op.f('ix_coffee_shop_equipment_grinder_1'), table_name='coffee_shop_equipment')
    op.drop_index(op.f('ix_coffee_shop_equipment_coffee_machine'), table_name='coffee_shop_equipment')
    op.drop_table('coffee_shop_equipment')
    op.drop_table('role')
    op.drop_index(op.f('ix_expense_type_cost'), table_name='expense')
    op.drop_index(op.f('ix_expense_timestamp'), table_name='expense')
    op.drop_index(op.f('ix_expense_category'), table_name='expense')
    op.drop_table('expense')
    op.drop_index(op.f('ix_coffee_shop_place_name'), table_name='coffee_shop')
    op.drop_index(op.f('ix_coffee_shop_address'), table_name='coffee_shop')
    op.drop_table('coffee_shop')
    op.drop_index(op.f('ix_barista_name'), table_name='barista')
    op.drop_table('barista')
    # ### end Alembic commands ###
