"""Update CoffeeShop relations

Revision ID: 465ce0f364a1
Revises: 5a64ff1befa8
Create Date: 2021-09-27 21:10:18.611365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '465ce0f364a1'
down_revision = '5a64ff1befa8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('barista', sa.Column('coffee_shop_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'barista', 'coffee_shop', ['coffee_shop_id'], ['id'])
    op.add_column('expense', sa.Column('coffee_shop_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'expense', 'coffee_shop', ['coffee_shop_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'expense', type_='foreignkey')
    op.drop_column('expense', 'coffee_shop_id')
    op.drop_constraint(None, 'barista', type_='foreignkey')
    op.drop_column('barista', 'coffee_shop_id')
    # ### end Alembic commands ###
