"""WriteOff add product_name column

Revision ID: 536d087b9e49
Revises: a721756a8dcf
Create Date: 2021-10-04 21:30:59.796355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '536d087b9e49'
down_revision = 'a721756a8dcf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('write_off', sa.Column('product_name', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('write_off', 'product_name')
    # ### end Alembic commands ###
