"""Replace Integer on Warehouse, coffee_arabica, coffee_blend and milk to Float

Revision ID: 5d5320430c93
Revises: 0d4603bb79a0
Create Date: 2021-09-26 18:23:19.048846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d5320430c93'
down_revision = '0d4603bb79a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_expense_category', table_name='expense')
    op.create_index(op.f('ix_expense_category'), 'expense', ['category'], unique=False)
    op.drop_index('ix_expense_type_cost', table_name='expense')
    op.create_index(op.f('ix_expense_type_cost'), 'expense', ['type_cost'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_expense_type_cost'), table_name='expense')
    op.create_index('ix_expense_type_cost', 'expense', ['type_cost'], unique=False)
    op.drop_index(op.f('ix_expense_category'), table_name='expense')
    op.create_index('ix_expense_category', 'expense', ['category'], unique=False)
    # ### end Alembic commands ###
