"""TransferProduct to one to one

Revision ID: 6f9d8f1efa95
Revises: da184f7d6fa2
Create Date: 2021-12-05 14:10:21.211552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f9d8f1efa95'
down_revision = 'da184f7d6fa2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transfer_products')
    op.add_column('transfer_product', sa.Column('where_shop', sa.String(length=64), nullable=True))
    op.add_column('transfer_product', sa.Column('to_shop', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_transfer_product_to_shop'), 'transfer_product', ['to_shop'], unique=False)
    op.create_index(op.f('ix_transfer_product_where_shop'), 'transfer_product', ['where_shop'], unique=False)
    op.drop_constraint('transfer_product_where_shop_id_fkey', 'transfer_product', type_='foreignkey')
    op.drop_column('transfer_product', 'where_shop_id')
    op.drop_column('transfer_product', 'to_shop_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transfer_product', sa.Column('to_shop_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('transfer_product', sa.Column('where_shop_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('transfer_product_where_shop_id_fkey', 'transfer_product', 'shop', ['where_shop_id'], ['id'])
    op.drop_index(op.f('ix_transfer_product_where_shop'), table_name='transfer_product')
    op.drop_index(op.f('ix_transfer_product_to_shop'), table_name='transfer_product')
    op.drop_column('transfer_product', 'to_shop')
    op.drop_column('transfer_product', 'where_shop')
    op.create_table('transfer_products',
    sa.Column('transfer_product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('shop_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shop.id'], name='transfer_products_shop_id_fkey'),
    sa.ForeignKeyConstraint(['transfer_product_id'], ['transfer_product.id'], name='transfer_products_transfer_product_id_fkey'),
    sa.PrimaryKeyConstraint('transfer_product_id', 'shop_id', name='transfer_products_pkey')
    )
    # ### end Alembic commands ###
