"""Rename hot_dogs to sausages, add buns

Revision ID: c2884864ed78
Revises: 704a45b48233
Create Date: 2021-11-28 09:55:36.457086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2884864ed78'
down_revision = '704a45b48233'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report', sa.Column('consumption_sausages', sa.Integer(), nullable=True))
    op.add_column('report', sa.Column('consumption_buns', sa.Integer(), nullable=True))
    op.add_column('report', sa.Column('sausages', sa.Integer(), nullable=True))
    op.add_column('report', sa.Column('buns', sa.Integer(), nullable=True))
    op.drop_column('report', 'consumption_hot_dogs')
    op.drop_column('report', 'hot_dogs')
    op.add_column('storage', sa.Column('sausages', sa.Integer(), nullable=True))
    op.add_column('storage', sa.Column('buns', sa.Integer(), nullable=True))
    op.drop_column('storage', 'hot_dogs')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('storage', sa.Column('hot_dogs', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('storage', 'buns')
    op.drop_column('storage', 'sausages')
    op.add_column('report', sa.Column('hot_dogs', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('report', sa.Column('consumption_hot_dogs', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('report', 'buns')
    op.drop_column('report', 'sausages')
    op.drop_column('report', 'consumption_buns')
    op.drop_column('report', 'consumption_sausages')
    # ### end Alembic commands ###
