"""New model Supply

Revision ID: c47c25a9b62a
Revises: ed016b8239bc
Create Date: 2021-10-04 21:21:50.744373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c47c25a9b62a'
down_revision = 'ed016b8239bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supply',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('coffee_shop_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('type_cost', sa.String(length=64), nullable=True),
    sa.Column('money', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['coffee_shop_id'], ['coffee_shop.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supply_timestamp'), 'supply', ['timestamp'], unique=False)
    op.create_index(op.f('ix_supply_type_cost'), 'supply', ['type_cost'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_supply_type_cost'), table_name='supply')
    op.drop_index(op.f('ix_supply_timestamp'), table_name='supply')
    op.drop_table('supply')
    # ### end Alembic commands ###
