"""Add TransferProduct model

Revision ID: da184f7d6fa2
Revises: e034604a0d22
Create Date: 2021-12-05 13:52:23.224528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da184f7d6fa2'
down_revision = 'e034604a0d22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transfer_product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('barista_id', sa.Integer(), nullable=True),
    sa.Column('where_shop_id', sa.Integer(), nullable=True),
    sa.Column('to_shop_id', sa.Integer(), nullable=True),
    sa.Column('backdating', sa.Boolean(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_edit', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('product_name', sa.String(length=80), nullable=True),
    sa.Column('amount', sa.Float(precision=50), nullable=True),
    sa.ForeignKeyConstraint(['barista_id'], ['barista.id'], ),
    sa.ForeignKeyConstraint(['where_shop_id'], ['shop.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transfer_products',
    sa.Column('transfer_product_id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shop.id'], ),
    sa.ForeignKeyConstraint(['transfer_product_id'], ['transfer_product.id'], ),
    sa.PrimaryKeyConstraint('transfer_product_id', 'shop_id')
    )
    op.add_column('deposit_funds', sa.Column('shop_id', sa.Integer(), nullable=False))
    op.drop_constraint('deposit_funds_report_id_fkey', 'deposit_funds', type_='foreignkey')
    op.create_foreign_key(None, 'deposit_funds', 'shop', ['shop_id'], ['id'])
    op.drop_column('deposit_funds', 'report_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deposit_funds', sa.Column('report_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'deposit_funds', type_='foreignkey')
    op.create_foreign_key('deposit_funds_report_id_fkey', 'deposit_funds', 'report', ['report_id'], ['id'])
    op.drop_column('deposit_funds', 'shop_id')
    op.drop_table('transfer_products')
    op.drop_table('transfer_product')
    # ### end Alembic commands ###
