"""Add relations to Deposit and Collection Funds models

Revision ID: e034604a0d22
Revises: 0a8a9ab3e8fa
Create Date: 2021-12-04 09:47:15.750941

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e034604a0d22'
down_revision = '0a8a9ab3e8fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collection_fund',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('barista_id', sa.Integer(), nullable=True),
    sa.Column('shop_id', sa.Integer(), nullable=True),
    sa.Column('backdating', sa.Boolean(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_edit', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('type_cost', sa.String(length=64), nullable=True),
    sa.Column('money', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['barista_id'], ['barista.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shop.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collection_fund_type_cost'), 'collection_fund', ['type_cost'], unique=False)
    op.create_table('deposit_fund',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('barista_id', sa.Integer(), nullable=True),
    sa.Column('shop_id', sa.Integer(), nullable=True),
    sa.Column('backdating', sa.Boolean(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_edit', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('type_cost', sa.String(length=64), nullable=True),
    sa.Column('money', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['barista_id'], ['barista.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shop.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deposit_fund_type_cost'), 'deposit_fund', ['type_cost'], unique=False)
    op.add_column('collection_funds', sa.Column('collection_fund_id', sa.Integer(), nullable=False))
    op.alter_column('collection_funds', 'shop_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index('ix_collection_funds_type_cost', table_name='collection_funds')
    op.drop_constraint('collection_funds_barista_id_fkey', 'collection_funds', type_='foreignkey')
    op.create_foreign_key(None, 'collection_funds', 'collection_fund', ['collection_fund_id'], ['id'])
    op.drop_column('collection_funds', 'timestamp')
    op.drop_column('collection_funds', 'last_edit')
    op.drop_column('collection_funds', 'id')
    op.drop_column('collection_funds', 'backdating')
    op.drop_column('collection_funds', 'money')
    op.drop_column('collection_funds', 'barista_id')
    op.drop_column('collection_funds', 'type_cost')
    op.add_column('deposit_funds', sa.Column('deposit_fund_id', sa.Integer(), nullable=False))
    op.add_column('deposit_funds', sa.Column('report_id', sa.Integer(), nullable=False))
    op.drop_index('ix_deposit_funds_type_cost', table_name='deposit_funds')
    op.drop_constraint('deposit_funds_shop_id_fkey', 'deposit_funds', type_='foreignkey')
    op.drop_constraint('deposit_funds_barista_id_fkey', 'deposit_funds', type_='foreignkey')
    op.create_foreign_key(None, 'deposit_funds', 'deposit_fund', ['deposit_fund_id'], ['id'])
    op.create_foreign_key(None, 'deposit_funds', 'report', ['report_id'], ['id'])
    op.drop_column('deposit_funds', 'timestamp')
    op.drop_column('deposit_funds', 'last_edit')
    op.drop_column('deposit_funds', 'shop_id')
    op.drop_column('deposit_funds', 'id')
    op.drop_column('deposit_funds', 'backdating')
    op.drop_column('deposit_funds', 'money')
    op.drop_column('deposit_funds', 'barista_id')
    op.drop_column('deposit_funds', 'type_cost')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deposit_funds', sa.Column('type_cost', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.add_column('deposit_funds', sa.Column('barista_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('deposit_funds', sa.Column('money', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('deposit_funds', sa.Column('backdating', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('deposit_funds', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.add_column('deposit_funds', sa.Column('shop_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('deposit_funds', sa.Column('last_edit', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('deposit_funds', sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'deposit_funds', type_='foreignkey')
    op.drop_constraint(None, 'deposit_funds', type_='foreignkey')
    op.create_foreign_key('deposit_funds_barista_id_fkey', 'deposit_funds', 'barista', ['barista_id'], ['id'])
    op.create_foreign_key('deposit_funds_shop_id_fkey', 'deposit_funds', 'shop', ['shop_id'], ['id'])
    op.create_index('ix_deposit_funds_type_cost', 'deposit_funds', ['type_cost'], unique=False)
    op.drop_column('deposit_funds', 'report_id')
    op.drop_column('deposit_funds', 'deposit_fund_id')
    op.add_column('collection_funds', sa.Column('type_cost', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.add_column('collection_funds', sa.Column('barista_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('collection_funds', sa.Column('money', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('collection_funds', sa.Column('backdating', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('collection_funds', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.add_column('collection_funds', sa.Column('last_edit', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('collection_funds', sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'collection_funds', type_='foreignkey')
    op.create_foreign_key('collection_funds_barista_id_fkey', 'collection_funds', 'barista', ['barista_id'], ['id'])
    op.create_index('ix_collection_funds_type_cost', 'collection_funds', ['type_cost'], unique=False)
    op.alter_column('collection_funds', 'shop_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('collection_funds', 'collection_fund_id')
    op.drop_index(op.f('ix_deposit_fund_type_cost'), table_name='deposit_fund')
    op.drop_table('deposit_fund')
    op.drop_index(op.f('ix_collection_fund_type_cost'), table_name='collection_fund')
    op.drop_table('collection_fund')
    # ### end Alembic commands ###
