"""Update DailyReport, add consumption productions per day

Revision ID: ed016b8239bc
Revises: cb8d28f08884
Create Date: 2021-09-27 22:10:39.915702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed016b8239bc'
down_revision = 'cb8d28f08884'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_report', sa.Column('consumption_coffee_arabika', sa.Float(), nullable=True))
    op.add_column('daily_report', sa.Column('consumption_coffee_blend', sa.Float(), nullable=True))
    op.add_column('daily_report', sa.Column('consumption_milk', sa.Float(), nullable=True))
    op.add_column('daily_report', sa.Column('consumption_panini', sa.Integer(), nullable=True))
    op.add_column('daily_report', sa.Column('consumption_hot_dogs', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('daily_report', 'consumption_hot_dogs')
    op.drop_column('daily_report', 'consumption_panini')
    op.drop_column('daily_report', 'consumption_milk')
    op.drop_column('daily_report', 'consumption_coffee_blend')
    op.drop_column('daily_report', 'consumption_coffee_arabika')
    # ### end Alembic commands ###
