"""Init DB

Revision ID: f5ab33e4601f
Revises: 
Create Date: 2021-10-29 20:55:43.878917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5ab33e4601f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('coffee_shop',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('place_name', sa.String(length=64), nullable=True),
    sa.Column('address', sa.String(length=64), nullable=True),
    sa.Column('cash', sa.Integer(), nullable=True),
    sa.Column('cashless', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coffee_shop_address'), 'coffee_shop', ['address'], unique=True)
    op.create_index(op.f('ix_coffee_shop_place_name'), 'coffee_shop', ['place_name'], unique=True)
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('barista',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('phone_number', sa.String(length=120), nullable=True),
    sa.Column('salary_rate', sa.Integer(), nullable=True),
    sa.Column('coffee_shop_id', sa.Integer(), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['coffee_shop_id'], ['coffee_shop.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_index(op.f('ix_barista_name'), 'barista', ['name'], unique=True)
    op.create_table('by_weight',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('coffee_shop_id', sa.Integer(), nullable=True),
    sa.Column('product_name', sa.String(length=80), nullable=True),
    sa.Column('amount', sa.Float(precision=50), nullable=True),
    sa.Column('type_cost', sa.String(length=64), nullable=True),
    sa.Column('money', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['coffee_shop_id'], ['coffee_shop.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_by_weight_timestamp'), 'by_weight', ['timestamp'], unique=False)
    op.create_index(op.f('ix_by_weight_type_cost'), 'by_weight', ['type_cost'], unique=False)
    op.create_table('coffee_shop_equipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coffee_machine', sa.String(length=64), nullable=True),
    sa.Column('grinder_1', sa.String(length=64), nullable=True),
    sa.Column('grinder_2', sa.String(length=64), nullable=True),
    sa.Column('coffee_shop_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['coffee_shop_id'], ['coffee_shop.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coffee_shop_equipment_coffee_machine'), 'coffee_shop_equipment', ['coffee_machine'], unique=False)
    op.create_index(op.f('ix_coffee_shop_equipment_grinder_1'), 'coffee_shop_equipment', ['grinder_1'], unique=False)
    op.create_index(op.f('ix_coffee_shop_equipment_grinder_2'), 'coffee_shop_equipment', ['grinder_2'], unique=False)
    op.create_table('expense',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('is_global', sa.Boolean(), nullable=True),
    sa.Column('type_cost', sa.String(length=64), nullable=True),
    sa.Column('money', sa.Integer(), nullable=True),
    sa.Column('coffee_shop_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['coffee_shop_id'], ['coffee_shop.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expense_timestamp'), 'expense', ['timestamp'], unique=False)
    op.create_index(op.f('ix_expense_type_cost'), 'expense', ['type_cost'], unique=False)
    op.create_table('supply',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('coffee_shop_id', sa.Integer(), nullable=True),
    sa.Column('product_name', sa.String(length=80), nullable=True),
    sa.Column('amount', sa.Float(precision=50), nullable=True),
    sa.Column('type_cost', sa.String(length=64), nullable=True),
    sa.Column('money', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['coffee_shop_id'], ['coffee_shop.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supply_timestamp'), 'supply', ['timestamp'], unique=False)
    op.create_index(op.f('ix_supply_type_cost'), 'supply', ['type_cost'], unique=False)
    op.create_table('warehouse',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coffee_arabika', sa.Float(precision=50), nullable=True),
    sa.Column('coffee_blend', sa.Float(precision=50), nullable=True),
    sa.Column('milk', sa.Float(precision=50), nullable=True),
    sa.Column('panini', sa.Integer(), nullable=True),
    sa.Column('hot_dogs', sa.Integer(), nullable=True),
    sa.Column('coffee_shop_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['coffee_shop_id'], ['coffee_shop.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('write_off',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('coffee_shop_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(precision=50), nullable=True),
    sa.Column('product_name', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['coffee_shop_id'], ['coffee_shop.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_write_off_timestamp'), 'write_off', ['timestamp'], unique=False)
    op.create_table('baristas',
    sa.Column('barista_id', sa.Integer(), nullable=False),
    sa.Column('coffee_shop_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['barista_id'], ['barista.id'], ),
    sa.ForeignKeyConstraint(['coffee_shop_id'], ['coffee_shop.id'], ),
    sa.PrimaryKeyConstraint('barista_id', 'coffee_shop_id')
    )
    op.create_table('categories',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('expense_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['expense_id'], ['expense.id'], ),
    sa.PrimaryKeyConstraint('category_id', 'expense_id')
    )
    op.create_table('daily_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coffee_shop_id', sa.Integer(), nullable=True),
    sa.Column('barista_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('cashbox', sa.Integer(), nullable=True),
    sa.Column('remainder_of_day', sa.Integer(), nullable=True),
    sa.Column('cashless', sa.Integer(), nullable=True),
    sa.Column('cash_balance', sa.Integer(), nullable=True),
    sa.Column('actual_balance', sa.Integer(), nullable=True),
    sa.Column('consumption_coffee_arabika', sa.Float(precision=50), nullable=True),
    sa.Column('consumption_coffee_blend', sa.Float(precision=50), nullable=True),
    sa.Column('consumption_milk', sa.Float(precision=50), nullable=True),
    sa.Column('consumption_panini', sa.Integer(), nullable=True),
    sa.Column('consumption_hot_dogs', sa.Integer(), nullable=True),
    sa.Column('coffee_arabika', sa.Float(precision=50), nullable=True),
    sa.Column('coffee_blend', sa.Float(precision=50), nullable=True),
    sa.Column('milk', sa.Float(precision=50), nullable=True),
    sa.Column('panini', sa.Integer(), nullable=True),
    sa.Column('hot_dogs', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['barista_id'], ['barista.id'], ),
    sa.ForeignKeyConstraint(['coffee_shop_id'], ['coffee_shop.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('barista_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['barista_id'], ['barista.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], )
    )
    op.create_table('expenses',
    sa.Column('expense_id', sa.Integer(), nullable=False),
    sa.Column('daily_report_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['daily_report_id'], ['daily_report.id'], ),
    sa.ForeignKeyConstraint(['expense_id'], ['expense.id'], ),
    sa.PrimaryKeyConstraint('expense_id', 'daily_report_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('expenses')
    op.drop_table('roles')
    op.drop_table('daily_report')
    op.drop_table('categories')
    op.drop_table('baristas')
    op.drop_index(op.f('ix_write_off_timestamp'), table_name='write_off')
    op.drop_table('write_off')
    op.drop_table('warehouse')
    op.drop_index(op.f('ix_supply_type_cost'), table_name='supply')
    op.drop_index(op.f('ix_supply_timestamp'), table_name='supply')
    op.drop_table('supply')
    op.drop_index(op.f('ix_expense_type_cost'), table_name='expense')
    op.drop_index(op.f('ix_expense_timestamp'), table_name='expense')
    op.drop_table('expense')
    op.drop_index(op.f('ix_coffee_shop_equipment_grinder_2'), table_name='coffee_shop_equipment')
    op.drop_index(op.f('ix_coffee_shop_equipment_grinder_1'), table_name='coffee_shop_equipment')
    op.drop_index(op.f('ix_coffee_shop_equipment_coffee_machine'), table_name='coffee_shop_equipment')
    op.drop_table('coffee_shop_equipment')
    op.drop_index(op.f('ix_by_weight_type_cost'), table_name='by_weight')
    op.drop_index(op.f('ix_by_weight_timestamp'), table_name='by_weight')
    op.drop_table('by_weight')
    op.drop_index(op.f('ix_barista_name'), table_name='barista')
    op.drop_table('barista')
    op.drop_table('role')
    op.drop_index(op.f('ix_coffee_shop_place_name'), table_name='coffee_shop')
    op.drop_index(op.f('ix_coffee_shop_address'), table_name='coffee_shop')
    op.drop_table('coffee_shop')
    op.drop_table('category')
    # ### end Alembic commands ###
