"""Add permisions and role

Revision ID: f7ab36da14e8
Revises: 41a02719dde8
Create Date: 2021-08-15 20:55:39.244689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7ab36da14e8'
down_revision = '41a02719dde8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('barista_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['barista_id'], ['barista.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], )
    )
    op.drop_table('roles_users')
    op.add_column('barista', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('barista', sa.Column('active', sa.Boolean(), nullable=True))
    op.add_column('barista', sa.Column('confirmed_at', sa.DateTime(), nullable=True))
    op.create_unique_constraint(None, 'barista', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'barista', type_='unique')
    op.drop_column('barista', 'confirmed_at')
    op.drop_column('barista', 'active')
    op.drop_column('barista', 'email')
    op.create_table('roles_users',
    sa.Column('barista_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['barista_id'], ['barista.id'], name='roles_users_barista_id_fkey'),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], name='roles_users_role_id_fkey')
    )
    op.drop_table('permissions')
    # ### end Alembic commands ###
